arduinobot:

  # Arm Trajectory Controllers ---------------------------------------
  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3


  # Gripper Trajectory Controllers ---------------------------------------
  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_4

